/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-south-1",
    "aws_appsync_graphqlEndpoint": "https://aljj55q7zngdzcyftuxtc7d4qq.appsync-api.ap-south-1.amazonaws.com/graphql",
    "aws_appsync_region": "ap-south-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-kqn36ocxprev5e5fzo7vogjqra",
    "aws_cognito_identity_pool_id": "ap-south-1:065f5386-9f0b-42d7-84fc-52269ca6c265",
    "aws_cognito_region": "ap-south-1",
    "aws_user_pools_id": "ap-south-1_anZAQEyhC",
    "aws_user_pools_web_client_id": "496fj8ejv4ao7i1le1b12k4v8t",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ]
};


export default awsmobile;
